### PR TITLE
Replace KoanfValueStore with MapStore to fix config deep-merge

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

Turns out that Koanf doesn't actually do deep-merging of objects.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `fix`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update documentation.
- [x] Update tests.

### CODE REVIEW

**Comment by knadh** [comment]
Hi @ccremer, randomly stumbled upon this issue. koanf does [deep merges recursively](https://github.com/knadh/koanf/blob/fc597f4766eed3576416a84d6f85434efca133bc/maps/maps.go#L107). Would you be able to describe the issue so that it can be fixed in koanf?

**Comment by ccremer** [comment]
Hi, I'm curious how you randomly landed here :)

The testdata in the unit test should provide you start.
Given the following YAML:
```yaml
:globals:
  features:
    testing:
      enabled: true
      anotherKey: value

.github/workflows/release.yaml:
  features:
    testing:
      enabled: false
```
In this example, `:globals` is the dict that defines base values. When merging the dict of `.github/workflows/release.yaml` into one, I'd expect `features.testing.enabled=false` in the result as the dict under `.github/workflows/release.yaml` overrides `:globals`, which was the case. so far so good. 
However `features.testing.anotherKey` was completely missing in the resulting map.

**Comment by ccremer** [comment]
@knadh did that answer your question?

**Comment by knadh** [comment]
Whoops, lost track of this. I recreated your exact test case:

```go
func TestMerge2(t *testing.T) {
	src := map[string]interface{}{
		"globals": map[string]interface{}{
			"features": map[string]interface{}{
				"testing": map[string]interface{}{
					"enabled": false,
				},
			},
		},
	}

	dest := map[string]interface{}{
		"globals": map[string]interface{}{
			"features": map[string]interface{}{
				"testing": map[string]interface{}{
					"enabled":    true,
					"anotherKey": "value",
				},
			},
		},
	}

	Merge(src, dest)
	fmt.Println(dest)
}
```

```shell
$ go test                                                                                                                                                                                 
map[globals:map[features:map[testing:map[anotherKey:value enabled:false]]]]
```

`anotherKey` is not lost in the result. Swapping `src` and `dest` don't cause the key to disappear either.

**Comment by ccremer** [comment]
hm, interesting!
Maybe I'll do another round of investigation later, maybe the root cause was something else.

**Comment by ccremer** [comment]
@knadh I'm picking up here and I've found the culprit.

I wasn't using `maps.Merge`, but `k.Unmarshal`, like this:
```go
data := make(map[string]interface{})
err := k.Unmarshal(":globals", &data)
// ...
err := k.Unmarshal(".github/workflows/release.yaml", &data) // I was expecting data to be merged
```
However, the 2nd unmarshalling removed `anotherKey`.
I guess this was a design oversight and nothing wrong with koanf after all.

If the 2nd overwrite is using `Cut()` instead, it works.

So my map is now retrieved with:
```go
merged := root.Cut(":globals")
// ...
err := merged.Merge(root.Cut(".github/workflows/release.yaml"))
// ...
return merged.Raw()
```

**Pull request merged**
